overblog_graphql:
    definitions:
        schema:
            query: RootQuery
            mutation: RootMutation
        mappings:
            types:
                -
                    type: yaml
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: null
        builders:
            args:
                Pager: "App\\GraphQL\\Args\\Pager"
