AddUserInput:
    type: relay-mutation-input
    config:
        description: 'Input of addUser mutation'
        fields:
            username:
                type: 'String!'
                description: 'The display name of the user'
            email:
                type: 'String!'
                description: 'The email address of the user'
            password:
                type: 'String!'
                description: 'Password of the user'
            firstname:
                type: 'String'
                description: 'The first name of the user'
            lastname:
                type: 'String'
                description: 'The last name of the user'
            wai_enabled:
                type: 'Boolean'
                description: 'Has the user the simplified interface?'
            roles:
                type: '[Roles]'
                description: 'The different roles of the user'
