RootMutation:
    type: object
    config:
        fields:
            NewUser:
                type: User
                description: "Add a new user"
                resolve: "@=mutation('NewUser', [args['input']['username'], args['input']['email'], args['input']['firstname'], args['input']['lastname'], args['input']['roles'], args['input']['wai_enabled'], args['input']['password']])"
                args:
                    input:
                        type: UserInput!
