UserList:
    type: object
    config:
        description: "Recover the list of users the current user can handle."
        fields:
            users:
                type: "[User]"
                description: "User details"

